***
# 3.1 First Order Syntax for Bird 22
### JX, 08/07/2022
***
    Bird22:
    LS110593.9.8.2018Araluen.WAV
    LS110640.10.1.2018Araluen.WAV
    
***

In [1]:
indv = 'Bird22'

In [2]:
## Load up Note Dataframe

import pandas as pd
from pathlib2 import Path

from butcherbird.utils.paths import DATA_DIR

SAVE_LOC = 'interim/fine_labels/butcherbird_note_df_'+indv+'_fine.pickle'
SAVE_LOC = DATA_DIR / SAVE_LOC

note_df = pd.read_pickle(SAVE_LOC)

## Make a copy of recursively generated labels
#note_df['lasso_labels'] = note_df['recur_labels_id']

note_df

index  phrase_nb  phrase_strt   phrase_end  phrase_len  note_cnt  \
0         0          0     2.370000     4.240000    1.870000         8   
1         1          0     2.370000     4.240000    1.870000         8   
2         2          0     2.370000     4.240000    1.870000         8   
3         3          0     2.370000     4.240000    1.870000         8   
4         4          0     2.370000     4.240000    1.870000         8   
...     ...        ...          ...          ...         ...       ...   
3566   1077        216  7449.073765  7451.014733    1.940968         5   
3567   1078        216  7449.073765  7451.014733    1.940968         5   
3568   1079        216  7449.073765  7451.014733    1.940968         5   
3569   1080        217  7455.220000  7455.855543    0.635543         2   
3570   1081        217  7455.220000  7455.855543    0.635543         2   

      note_nb    note_strt     note_end  note_len  ...  \
0           0     2.370000     2.415699  0.045699  ...   
1           1     2.660000     2.977558  0.317558  ...   
2           2     3.079714     3.173357  0.093643  ...   
3           3     3.260000     3.581982  0.321982  ...   
4           4     3.664275     3.718191  0.053916  ...   
...       ...          ...          ...       ...  ...   
3566        2  7449.909933  7450.602325  0.692392  ...   
3567        3  7450.606109  7450.790000  0.183891  ...   
3568        4  7450.880000  7451.014733  0.134733  ...   
3569        0  7455.220000  7455.440000  0.220000  ...   
3570        1  7455.670000  7455.855543  0.185543  ...   

                               key  \
0      LS110593.9.8.2018Araluen_dn   
1      LS110593.9.8.2018Araluen_dn   
2      LS110593.9.8.2018Araluen_dn   
3      LS110593.9.8.2018Araluen_dn   
4      LS110593.9.8.2018Araluen_dn   
...                            ...   
3566  LS110640.10.1.2018Araluen_dn   
3567  LS110640.10.1.2018Araluen_dn   
3568  LS110640.10.1.2018Araluen_dn   
3569  LS110640.10.1.2018Araluen_dn   
3570  LS110640.10.1.2018Araluen_dn   

                                                  audio   rate  \
0     [0.0, -5.558967174674641e-06, -5.2225732263302...  48000   
1     [0.0, 3.069944854750729e-05, 4.037410245845782...  48000   
2     [0.0, 0.0030796517861769505, 0.008741865222086...  48000   
3     [-0.0, -0.00020854328852771913, -0.00037995893...  48000   
4     [-0.0, -0.0018707999847079283, -0.003892325714...  48000   
...                                                 ...    ...   
3566  [-0.0, -2.140440722621177e-07, -3.212511081611...  48000   
3567  [0.0, 6.060969809557767e-05, 0.000226911032359...  48000   
3568  [-0.0, -0.0002617451218550637, -0.000495686777...  48000   
3569  [0.0, 4.403572842078721e-05, 6.391323052796741...  48000   
3570  [0.0, 1.7624285897152536e-05, 1.44506010833202...  48000   

                                            spectrogram  \
0     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
1     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
2     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
4     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
...                                                 ...   
3566  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3567  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3568  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3569  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3570  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   

                         umap hdbscan_labels                recur_labels  \
0      [12.999457, -3.640876]              5   5|1|0|1.0|1.0|1.0|0.0|nan   
1      [14.162895, 10.566473]             19  19|1|0|0.0|0.0|nan|nan|nan   
2       [5.823101, 11.083305]             19  19|1|1|0.0|0.0|0.0|nan|nan   
3     [-3.8884213, 19.716284]              3   3|0|2|0.0|nan|nan|nan|nan   
4      [4.6038485, 3.3076212]              7   7|1|0|0.0|0.0|nan|nan|nan   
...  

## Feed parameters into analysis package

In [3]:
onsets = note_df['note_strt']
syntactic_units = note_df['lasso_labels']
expected_interval_range = [0, 1]
dataset_description = 'Songbird: Pied Butcherbirds'

## Find Consistent Transitions

In [4]:
from butcherbird import sequential

In [5]:
import numpy as np

In [6]:
trans_mat = sequential.construct_seq_matrix(note_df, label = 'lasso_labels', sort = False)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]


In [7]:
## bootstrap null distributions with 100 samples under 0-order syntax assumption

In [8]:
p_container = []

## sample 100 times
for i in np.arange(0, 100):
    
    ## bootstrap one zero-order sequence
    bootstrapped_df = note_df.sample(n = len(note_df), replace = True).reset_index()
    
    ## find the transition matrix of the sequence
    bootstrapped_mat = sequential.construct_seq_matrix(bootstrapped_df, label = 'lasso_labels', sort = False)
    
    ## turn the matrix into long form
    bootstrapped_long = sequential.long_cvtr(bootstrapped_mat, songType = 'Bootstrapped')
    
    ## return bootstrapped distribution of all transition probabilities
    p_container.append(bootstrapped_long.p.values)
    
p_container

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 32 33 34 35 36 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 

[array([0.01075269, 0.02150538, 0.05376344, ..., 0.00286533, 0.        ,
        0.08022923]),
 array([0.03603604, 0.00900901, 0.01801802, ..., 0.01234568, 0.        ,
        0.08950617]),
 array([0.00900901, 0.00900901, 0.02702703, ..., 0.01328904, 0.        ,
        0.08637874]),
 array([0.02884615, 0.00961538, 0.01923077, ..., 0.00598802, 0.        ,
        0.10479042]),
 array([0.01923077, 0.00961538, 0.02884615, ..., 0.02068966, 0.        ,
        0.09310345]),
 array([0.01098901, 0.        , 0.06593407, ..., 0.01420455, 0.        ,
        0.10511364]),
 array([0.05128205, 0.00854701, 0.00854701, ..., 0.01582278, 0.        ,
        0.08544304]),
 array([0.03636364, 0.02727273, 0.00909091, ..., 0.01506024, 0.        ,
        0.06927711]),
 array([0.03157895, 0.        , 0.02105263, ..., 0.01156069, 0.        ,
        0.11560694]),
 array([0.04201681, 0.        , 0.05882353, ..., 0.009375  , 0.        ,
        0.096875  ]),
 array([0.04385965, 0.01754386, 0.02631579, ..., 0

In [9]:
## swap axes so that each element in p_container is a null sampling distribution of 
## find how likely that specific transition happpens with just 0 order syntax

In [10]:
p = np.swapaxes(p_container, 0, 1)

In [11]:
p

array([[0.01075269, 0.03603604, 0.00900901, ..., 0.0212766 , 0.03191489,
        0.04395604],
       [0.02150538, 0.00900901, 0.00900901, ..., 0.0106383 , 0.03191489,
        0.01098901],
       [0.05376344, 0.01801802, 0.02702703, ..., 0.0212766 , 0.        ,
        0.01098901],
       ...,
       [0.00286533, 0.01234568, 0.01328904, ..., 0.01139601, 0.00911854,
        0.01396648],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.0027933 ],
       [0.08022923, 0.08950617, 0.08637874, ..., 0.10826211, 0.10334347,
        0.12290503]])

In [12]:
import numpy as np
import scipy.stats

## a standard calculation for confidence interval
def mean_confidence_interval(data, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1 + confidence) / 2., n-1)
    return m, m-h, m+h

In [13]:
higherconfints = []

for null_transitions in p:
    higherconfints.append(mean_confidence_interval(null_transitions, confidence = 0.95)[2])
    
higherconfints

[0.03313340592494233,
 0.011910356376237356,
 0.026898921743176055,
 0.027900541333871348,
 0.004895489797797536,
 0.020431953287116996,
 0.05600366347198023,
 0.030189078894324886,
 0.01289269299734132,
 0.02263246744131735,
 0.03408280087643733,
 0.023627627311553157,
 0.007497306575820694,
 0.015818799386608455,
 0.03257119579285737,
 0.02253295004032191,
 0.032027443365366344,
 0.0408076517423485,
 0.03070890864086799,
 0.03071821065522766,
 0.032579025398722025,
 0.08255686083478701,
 0.0014108664593935393,
 0.09338716318089486,
 0.0786290066453328,
 0.015427876027574868,
 0.021638009547251636,
 0.012612728269730835,
 0.04737841798861017,
 0.08007964895174091,
 0.0017182060097920885,
 0.0011381105053321363,
 0.0024236901413293354,
 0.005524949330396656,
 0.0005630999619766486,
 0.0015137873173370463,
 0.01384189316465045,
 0.0004454759679688616,
 0.09361691456924387,
 0.039106807002799546,
 0.011007898633936445,
 0.027950001302482028,
 0.029960608929531847,
 0.005171858949967577,


In [14]:
trans_long = sequential.long_cvtr(trans_mat, songType = 'True')

In [15]:
trans_long

songType  noteType  markov        p
0        True         0       0  0.00000
1        True         0       1  0.00000
2        True         0       2  0.00000
3        True         0       3  0.87619
4        True         0       4  0.00000
...       ...       ...     ...      ...
1516     True        38      34  0.00000
1517     True        38      35  0.00000
1518     True        38      36  0.00000
1519     True        38      37  0.00000
1520     True        38      38  0.21194

[1521 rows x 4 columns]

In [16]:
trans_long['higherconfint'] = higherconfints

In [17]:
trans_long

songType  noteType  markov        p  higherconfint
0        True         0       0  0.00000       0.033133
1        True         0       1  0.00000       0.011910
2        True         0       2  0.00000       0.026899
3        True         0       3  0.87619       0.027901
4        True         0       4  0.00000       0.004895
...       ...       ...     ...      ...            ...
1516     True        38      34  0.00000       0.001003
1517     True        38      35  0.00000       0.001285
1518     True        38      36  0.00000       0.012646
1519     True        38      37  0.00000       0.000471
1520     True        38      38  0.21194       0.098129

[1521 rows x 5 columns]

In [18]:
filtered_trans_long = trans_long[trans_long.p > trans_long.higherconfint]

In [19]:
filtered_trans_long

songType  noteType  markov         p  higherconfint
3        True         0       3  0.876190       0.027901
48       True         1       9  0.029412       0.023074
49       True         1      10  0.294118       0.030189
59       True         1      20  0.088235       0.035745
62       True         1      23  0.205882       0.088073
...       ...       ...     ...       ...            ...
1487     True        38       5  0.026866       0.022404
1493     True        38      11  0.140299       0.019681
1496     True        38      14  0.235821       0.026636
1498     True        38      16  0.259701       0.028532
1520     True        38      38  0.211940       0.098129

[154 rows x 5 columns]

In [20]:
ftl = filtered_trans_long

## Rhythm Dyadic Analysis

In [21]:
## load rhythm analyzer
import butcherbird.rhythm as rhythm

/home/AD/j8xing/syntax_rhythm_pbb/butcherbird/rhythm.py:151: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


In [22]:
dyadic = rhythm.construct_rhythm_df(
    onsets = onsets, 
    syntactic_units = syntactic_units, 
    expected_interval_range = expected_interval_range)

In [23]:
dyadic

intervals1  intervals2  label1  label2  label3  s_interval  l_interval  \
746     0.018920    0.015573      26      26       5    0.015573    0.018920   
1275    0.049143    0.007020      38      26      38    0.007020    0.049143   
2146    0.054145    0.019306      38      26       6    0.019306    0.054145   
12      0.042565    0.048240      27      28       8    0.042565    0.048240   
2634    0.055795    0.056753      25      38      14    0.055795    0.056753   
...          ...         ...     ...     ...     ...         ...         ...   
509     0.555021    0.895000      20      18       6    0.555021    0.895000   
1609    0.707663    0.752358      20      18       0    0.707663    0.752358   
427     0.670000    0.830021      20      16       0    0.670000    0.830021   
3343    0.555399    0.965593      19       1      23    0.555399    0.965593   
1143    0.792418    0.737603      20      18       0    0.737603    0.792418   

      cycle_dur  ratio_roeske  ratio_custom  cycle_rank  
746    0.034493      0.548518      0.823094           1  
1275   0.056163      0.875000      0.142857           2  
2146   0.073452      0.737159      0.356560           3  
12     0.090806      0.468750      0.882353           4  
2634   0.112549      0.495744      0.983118           5  
...         ...           ...           ...         ...  
509    1.450021      0.382767      0.620135        2295  
1609   1.460021      0.484694      0.940593        2296  
427    1.500021      0.446660      0.807209        2297  
3343   1.520993      0.365156      0.575190        2298  
1143   1.530021      0.517913      0.930825        2299  

[2299 rows x 11 columns]

In [24]:
ftl

songType  noteType  markov         p  higherconfint
3        True         0       3  0.876190       0.027901
48       True         1       9  0.029412       0.023074
49       True         1      10  0.294118       0.030189
59       True         1      20  0.088235       0.035745
62       True         1      23  0.205882       0.088073
...       ...       ...     ...       ...            ...
1487     True        38       5  0.026866       0.022404
1493     True        38      11  0.140299       0.019681
1496     True        38      14  0.235821       0.026636
1498     True        38      16  0.259701       0.028532
1520     True        38      38  0.211940       0.098129

[154 rows x 5 columns]

In [25]:
## verify rhythm counts above 0.01 of total rhythm count (8013 * 0.01)

In [26]:
verified = []

for index, transition in ftl.iterrows():
    note = transition.noteType
    dest = transition.markov
    
    ## find if dyadic contains enough entries for this particular combination
    first_filter = dyadic[dyadic.label1 == note]
    second_filter = first_filter[first_filter.label2 == dest]
    
    if len(second_filter) > 0.01*len(dyadic):
        verified.append(index)

In [27]:
vr = ftl.filter(items = verified, axis = 0)

In [28]:
unique, counts = np.unique(vr.noteType, return_counts = True)

In [29]:
eligible_notes = []
for noteType, count in zip(unique, counts):
    if count > 1:
        eligible_notes.append(noteType)

In [30]:
eligible_transitions = []

for n in eligible_notes:
    eligible_transitions.append(vr[vr.noteType == n])
    
eligible_transitions = pd.concat(eligible_transitions)

In [31]:
eligible_transitions

songType  noteType  markov         p  higherconfint
249      True         6      15  0.317204       0.027058
272      True         6      38  0.408602       0.095878
637      True        16      13  0.428571       0.017370
649      True        16      25  0.527473       0.014692
689      True        17      26  0.271318       0.021622
691      True        17      28  0.581395       0.046971
842      True        21      23  0.369963       0.088070
848      True        21      29  0.241758       0.077558
899      True        23       2  0.289389       0.026281
914      True        23      17  0.382637       0.038108
924      True        23      27  0.083601       0.011883
933      True        23      36  0.102894       0.013510
955      True        24      19  0.274436       0.025999
960      True        24      24  0.406015       0.078054
1098     True        28       6  0.465409       0.053345
1115     True        28      23  0.515723       0.093337
1498     True        38      16  0.259701       0.028532
1520     True        38      38  0.211940       0.098129

In [32]:
import scipy.stats
import itertools

def bif_rhythm_ks(vd_bif, dyadic, mode = 'ratio_roeske'):
    '''
    Calculate KS test for each bifurcation point
    '''
    
    output = []
    
    # 1. Extract Bifurcation Info from vd_bif
    ### a. Find all pre-bifurcation notes
    pre_bif = np.unique(vd_bif['noteType'])
    
    # 2. For each bifurcation, conduct a Kolmogorov-Smirnov test
    ### a. for each bifurcation
    for note in pre_bif:
        ### a. Query its exact slice
        bif_df = vd_bif[vd_bif['noteType'] == note]
        ### b. Query its bifurcation destinations
        destinations = np.unique(bif_df['markov'])
        pairs = list(itertools.combinations(destinations, 2))
        ### c. Filter dyadic by pre_bif
        note_df = dyadic[dyadic['label1'] == note]
        ### d. Filter note_df by bif destinations
        for pair in pairs: 
            t1_df = note_df[note_df['label2'] == pair[0]]
            t2_df = note_df[note_df['label2'] == pair[1]]
            bif_prob0 = bif_df[bif_df['markov'] == pair[0]]['p'].values[0]
            bif_prob1 = bif_df[bif_df['markov'] == pair[1]]['p'].values[0]
            
            ### e. compute ks
            try:
                ks = scipy.stats.ks_2samp(t1_df[mode], t2_df[mode])
            except:
                ks = [None, None]
                print('ks not computed')
            ### e. feeds out pandas
            output.append(
                pd.DataFrame(
                    {
                        'pre_bif': [note],
                        'bif_des': [(pair[0], pair[1])],
                        'bif_prof': [
                            (
                                bif_prob0,
                                bif_prob1
                            )
                        ],
                        'rhy_cnts': [
                            (
                                len(t1_df),
                                len(t2_df)
                            )
                        ],
                        'ks_statistic': [ks[0]],
                        'ks_p': [ks[1]]
                    }
                )
            )
        
        print('Finished querying bifurcation with pre_bif ', note)
    return pd.concat(output)

In [33]:
entangle = bif_rhythm_ks(eligible_transitions, dyadic)

Finished querying bifurcation with pre_bif  6
Finished querying bifurcation with pre_bif  16
Finished querying bifurcation with pre_bif  17
Finished querying bifurcation with pre_bif  21
Finished querying bifurcation with pre_bif  23
Finished querying bifurcation with pre_bif  24
Finished querying bifurcation with pre_bif  28
Finished querying bifurcation with pre_bif  38


In [34]:
entangle

pre_bif   bif_des                                    bif_prof   rhy_cnts  \
0        6  (15, 38)   (0.3172043010752688, 0.40860215053763443)   (59, 75)   
0       16  (13, 25)   (0.42857142857142855, 0.5274725274725275)   (39, 48)   
0       17  (26, 28)    (0.2713178294573643, 0.5813953488372093)   (34, 75)   
0       21  (23, 29)     (0.36996336996337, 0.24175824175824176)  (100, 66)   
0       23   (2, 17)  (0.28938906752411575, 0.38263665594855306)  (90, 117)   
0       23   (2, 27)  (0.28938906752411575, 0.08360128617363344)   (90, 25)   
0       23   (2, 36)  (0.28938906752411575, 0.10289389067524116)   (90, 32)   
0       23  (17, 27)  (0.38263665594855306, 0.08360128617363344)  (117, 25)   
0       23  (17, 36)  (0.38263665594855306, 0.10289389067524116)  (117, 32)   
0       23  (27, 36)  (0.08360128617363344, 0.10289389067524116)   (25, 32)   
0       24  (19, 24)   (0.2744360902255639, 0.40601503759398494)   (26, 70)   
0       28   (6, 23)   (0.46540880503144655, 0.5157232704402516)   (69, 82)   
0       38  (16, 38)  (0.25970149253731345, 0.21194029850746268)   (87, 47)   

   ks_statistic          ks_p  
0      0.986667  2.071676e-37  
0      0.751603  2.109416e-12  
0      0.134118  7.335003e-01  
0      0.974848  9.869535e-44  
0      0.264957  1.217930e-03  
0      1.000000  1.575693e-25  
0      1.000000  7.917690e-30  
0      1.000000  4.569218e-28  
0      1.000000  5.485083e-33  
0      0.145000  8.761763e-01  
0      0.586813  1.209256e-06  
0      0.131495  4.833624e-01  
0      1.000000  5.470453e-37

In [35]:
entangle['ks_p'] < 0.05

0     True
0     True
0    False
0     True
0     True
0     True
0     True
0     True
0     True
0    False
0     True
0    False
0     True
Name: ks_p, dtype: bool

In [36]:
## bonferroni correct

In [37]:
import statsmodels.stats.multitest

In [38]:
entangle['bonferroni_p'] = statsmodels.stats.multitest.multipletests(entangle['ks_p'].values, alpha = 0.05, method = 'bonferroni')[1]

In [39]:
entangle

pre_bif   bif_des                                    bif_prof   rhy_cnts  \
0        6  (15, 38)   (0.3172043010752688, 0.40860215053763443)   (59, 75)   
0       16  (13, 25)   (0.42857142857142855, 0.5274725274725275)   (39, 48)   
0       17  (26, 28)    (0.2713178294573643, 0.5813953488372093)   (34, 75)   
0       21  (23, 29)     (0.36996336996337, 0.24175824175824176)  (100, 66)   
0       23   (2, 17)  (0.28938906752411575, 0.38263665594855306)  (90, 117)   
0       23   (2, 27)  (0.28938906752411575, 0.08360128617363344)   (90, 25)   
0       23   (2, 36)  (0.28938906752411575, 0.10289389067524116)   (90, 32)   
0       23  (17, 27)  (0.38263665594855306, 0.08360128617363344)  (117, 25)   
0       23  (17, 36)  (0.38263665594855306, 0.10289389067524116)  (117, 32)   
0       23  (27, 36)  (0.08360128617363344, 0.10289389067524116)   (25, 32)   
0       24  (19, 24)   (0.2744360902255639, 0.40601503759398494)   (26, 70)   
0       28   (6, 23)   (0.46540880503144655, 0.5157232704402516)   (69, 82)   
0       38  (16, 38)  (0.25970149253731345, 0.21194029850746268)   (87, 47)   

   ks_statistic          ks_p  bonferroni_p  
0      0.986667  2.071676e-37  2.693178e-36  
0      0.751603  2.109416e-12  2.742240e-11  
0      0.134118  7.335003e-01  1.000000e+00  
0      0.974848  9.869535e-44  1.283040e-42  
0      0.264957  1.217930e-03  1.583309e-02  
0      1.000000  1.575693e-25  2.048401e-24  
0      1.000000  7.917690e-30  1.029300e-28  
0      1.000000  4.569218e-28  5.939983e-27  
0      1.000000  5.485083e-33  7.130608e-32  
0      0.145000  8.761763e-01  1.000000e+00  
0      0.586813  1.209256e-06  1.572033e-05  
0      0.131495  4.833624e-01  1.000000e+00  
0      1.000000  5.470453e-37  7.111589e-36

In [40]:
entangle['bonferroni_p'] < 0.05

0     True
0     True
0    False
0     True
0     True
0     True
0     True
0     True
0     True
0    False
0     True
0    False
0     True
Name: bonferroni_p, dtype: bool

In [41]:
## do a shuffle
dyadic_shuffle = dyadic.copy(deep = True)
np.random.shuffle(dyadic_shuffle['ratio_roeske'].values)
entangle_shuffled = bif_rhythm_ks(eligible_transitions, dyadic_shuffle)

Finished querying bifurcation with pre_bif  6
Finished querying bifurcation with pre_bif  16
Finished querying bifurcation with pre_bif  17
Finished querying bifurcation with pre_bif  21
Finished querying bifurcation with pre_bif  23
Finished querying bifurcation with pre_bif  24
Finished querying bifurcation with pre_bif  28
Finished querying bifurcation with pre_bif  38


In [42]:
entangle_shuffled

pre_bif   bif_des                                    bif_prof   rhy_cnts  \
0        6  (15, 38)   (0.3172043010752688, 0.40860215053763443)   (59, 75)   
0       16  (13, 25)   (0.42857142857142855, 0.5274725274725275)   (39, 48)   
0       17  (26, 28)    (0.2713178294573643, 0.5813953488372093)   (34, 75)   
0       21  (23, 29)     (0.36996336996337, 0.24175824175824176)  (100, 66)   
0       23   (2, 17)  (0.28938906752411575, 0.38263665594855306)  (90, 117)   
0       23   (2, 27)  (0.28938906752411575, 0.08360128617363344)   (90, 25)   
0       23   (2, 36)  (0.28938906752411575, 0.10289389067524116)   (90, 32)   
0       23  (17, 27)  (0.38263665594855306, 0.08360128617363344)  (117, 25)   
0       23  (17, 36)  (0.38263665594855306, 0.10289389067524116)  (117, 32)   
0       23  (27, 36)  (0.08360128617363344, 0.10289389067524116)   (25, 32)   
0       24  (19, 24)   (0.2744360902255639, 0.40601503759398494)   (26, 70)   
0       28   (6, 23)   (0.46540880503144655, 0.5157232704402516)   (69, 82)   
0       38  (16, 38)  (0.25970149253731345, 0.21194029850746268)   (87, 47)   

   ks_statistic      ks_p  
0      0.105989  0.801987  
0      0.190705  0.358082  
0      0.132941  0.740586  
0      0.102424  0.751056  
0      0.088034  0.786432  
0      0.202222  0.350425  
0      0.200694  0.255673  
0      0.213333  0.259734  
0      0.169071  0.415968  
0      0.336250  0.063264  
0      0.128571  0.864288  
0      0.151113  0.317052  
0      0.189044  0.192809

# Compute Global Statistic

The concept of the global statistic here is to compare the rhythm ratios for each first-order syntax and to compare between-group variation / within-group variation. 

1. Find each first-order transition -> z-score -> compile all first-order transition -> MSE
2. Compare with zero-order transition -> z-score -> compile all first-order transition -> MSE
3. Is first-order transition variance is lower than zero-order transition variance?

## Let's find all the first-order transitions first

In [43]:
import scipy.stats as stats

In [44]:
def syntactic_rhythmic_modulation_metric (dyadic):
    
    ## compute global metric
    
    first_order_rhythms_centered = []
    first_order_group_n = 0

    ## for every possible label
    for label in np.unique(dyadic['label1']):

        ## find a sub dataframe containing only designated zero-order label
        zero_order = dyadic[dyadic['label1'] == label]

        ## for every possible transition of that label
        for transition in np.unique(zero_order['label2']):

            ## find its rhythms
            first_order = zero_order[zero_order['label2'] == transition]
            first_order_rhythms = first_order['ratio_roeske'].values
            first_order_rhythms_centered.extend(first_order_rhythms - np.mean(first_order_rhythms))

            ## add 1 to group_n
            first_order_group_n+=1
    
    # find MSE
    MSE_first = sum(np.square(first_order_rhythms_centered)) / len(dyadic)
    MSE_baseline = sum(np.square(dyadic['ratio_roeske'].values - np.mean(dyadic['ratio_roeske']))) / len(dyadic)
    
    return 1 - MSE_first / MSE_baseline

## empirical 

In [45]:
syntactic_rhythmic_modulation_metric(dyadic)

0.9487572086684568

## Find Baseline using bootstrap

In [46]:
from tqdm.autonotebook import tqdm

In [47]:
dyadic_shuffle = dyadic.copy(deep = True)

SDoMSE = []

for sample in tqdm(np.arange(0, 100)):
    
    ## shuffle dyadic
    np.random.shuffle(dyadic_shuffle['ratio_roeske'].values)
    
    SDoMSE.append(syntactic_rhythmic_modulation_metric(dyadic_shuffle))

  0%|          | 0/100 [00:00<?, ?it/s]

In [48]:
mean_confidence_interval(SDoMSE, confidence=0.95)

(0.06663556463127446, 0.06540832330625286, 0.06786280595629605)

In [49]:
syntactic_rhythmic_modulation_metric(dyadic)

0.9487572086684568

## try using anova

In [50]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [51]:
dyadic = dyadic.astype({'label1': str, 'label2': str})

In [52]:
model = ols('ratio_roeske ~ label1', data = dyadic).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
anova_table

sum_sq      df           F  PR(>F)
label1    66.512565    36.0  149.893268     0.0
Residual  27.881213  2262.0         NaN     NaN

In [53]:
dyadic['transition'] = dyadic['label1'] + '+' + dyadic['label2']

In [54]:
dyadic

intervals1  intervals2 label1 label2  label3  s_interval  l_interval  \
746     0.018920    0.015573     26     26       5    0.015573    0.018920   
1275    0.049143    0.007020     38     26      38    0.007020    0.049143   
2146    0.054145    0.019306     38     26       6    0.019306    0.054145   
12      0.042565    0.048240     27     28       8    0.042565    0.048240   
2634    0.055795    0.056753     25     38      14    0.055795    0.056753   
...          ...         ...    ...    ...     ...         ...         ...   
509     0.555021    0.895000     20     18       6    0.555021    0.895000   
1609    0.707663    0.752358     20     18       0    0.707663    0.752358   
427     0.670000    0.830021     20     16       0    0.670000    0.830021   
3343    0.555399    0.965593     19      1      23    0.555399    0.965593   
1143    0.792418    0.737603     20     18       0    0.737603    0.792418   

      cycle_dur  ratio_roeske  ratio_custom  cycle_rank transition  
746    0.034493      0.548518      0.823094           1      26+26  
1275   0.056163      0.875000      0.142857           2      38+26  
2146   0.073452      0.737159      0.356560           3      38+26  
12     0.090806      0.468750      0.882353           4      27+28  
2634   0.112549      0.495744      0.983118           5      25+38  
...         ...           ...           ...         ...        ...  
509    1.450021      0.382767      0.620135        2295      20+18  
1609   1.460021      0.484694      0.940593        2296      20+18  
427    1.500021      0.446660      0.807209        2297      20+16  
3343   1.520993      0.365156      0.575190        2298       19+1  
1143   1.530021      0.517913      0.930825        2299      20+18  

[2299 rows x 12 columns]

In [55]:
model = ols('ratio_roeske ~ transition', data = dyadic).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
anova_table

sum_sq      df           F  PR(>F)
transition  89.556778   153.0  259.572199     0.0
Residual     4.837001  2145.0         NaN     NaN