***
# 3.1 First Order Syntax for Bird 22
### JX, 03/15/2022
***
    Bird22:
    LS110593.9.8.2018Araluen.WAV
    LS110640.10.1.2018Araluen.WAV
    
***

In [1]:
indv = 'Bird22'

In [2]:
## Load up Note Dataframe

import pandas as pd
from pathlib2 import Path

from butcherbird.utils.paths import DATA_DIR

SAVE_LOC = 'interim/fine_labels/butcherbird_note_df_'+indv+'_fine.pickle'
SAVE_LOC = DATA_DIR / SAVE_LOC

note_df = pd.read_pickle(SAVE_LOC)

## Make a copy of recursively generated labels
#note_df['lasso_labels'] = note_df['recur_labels_id']

note_df

index  phrase_nb  phrase_strt   phrase_end  phrase_len  note_cnt  \
0         0          0     2.370000     4.240000    1.870000         8   
1         1          0     2.370000     4.240000    1.870000         8   
2         2          0     2.370000     4.240000    1.870000         8   
3         3          0     2.370000     4.240000    1.870000         8   
4         4          0     2.370000     4.240000    1.870000         8   
...     ...        ...          ...          ...         ...       ...   
3566   1077        216  7449.073765  7451.014733    1.940968         5   
3567   1078        216  7449.073765  7451.014733    1.940968         5   
3568   1079        216  7449.073765  7451.014733    1.940968         5   
3569   1080        217  7455.220000  7455.855543    0.635543         2   
3570   1081        217  7455.220000  7455.855543    0.635543         2   

      note_nb    note_strt     note_end  note_len  ...  \
0           0     2.370000     2.415699  0.045699  ...   
1           1     2.660000     2.977558  0.317558  ...   
2           2     3.079714     3.173357  0.093643  ...   
3           3     3.260000     3.581982  0.321982  ...   
4           4     3.664275     3.718191  0.053916  ...   
...       ...          ...          ...       ...  ...   
3566        2  7449.909933  7450.602325  0.692392  ...   
3567        3  7450.606109  7450.790000  0.183891  ...   
3568        4  7450.880000  7451.014733  0.134733  ...   
3569        0  7455.220000  7455.440000  0.220000  ...   
3570        1  7455.670000  7455.855543  0.185543  ...   

                               key  \
0      LS110593.9.8.2018Araluen_dn   
1      LS110593.9.8.2018Araluen_dn   
2      LS110593.9.8.2018Araluen_dn   
3      LS110593.9.8.2018Araluen_dn   
4      LS110593.9.8.2018Araluen_dn   
...                            ...   
3566  LS110640.10.1.2018Araluen_dn   
3567  LS110640.10.1.2018Araluen_dn   
3568  LS110640.10.1.2018Araluen_dn   
3569  LS110640.10.1.2018Araluen_dn   
3570  LS110640.10.1.2018Araluen_dn   

                                                  audio   rate  \
0     [0.0, -5.558967174674641e-06, -5.2225732263302...  48000   
1     [0.0, 3.069944854750729e-05, 4.037410245845782...  48000   
2     [0.0, 0.0030796517861769505, 0.008741865222086...  48000   
3     [-0.0, -0.00020854328852771913, -0.00037995893...  48000   
4     [-0.0, -0.0018707999847079283, -0.003892325714...  48000   
...                                                 ...    ...   
3566  [-0.0, -2.140440722621177e-07, -3.212511081611...  48000   
3567  [0.0, 6.060969809557767e-05, 0.000226911032359...  48000   
3568  [-0.0, -0.0002617451218550637, -0.000495686777...  48000   
3569  [0.0, 4.403572842078721e-05, 6.391323052796741...  48000   
3570  [0.0, 1.7624285897152536e-05, 1.44506010833202...  48000   

                                            spectrogram  \
0     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
1     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
2     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
4     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
...                                                 ...   
3566  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3567  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3568  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3569  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3570  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   

                         umap hdbscan_labels                recur_labels  \
0      [12.999457, -3.640876]              5   5|1|0|1.0|1.0|1.0|0.0|nan   
1      [14.162895, 10.566473]             19  19|1|0|0.0|0.0|nan|nan|nan   
2       [5.823101, 11.083305]             19  19|1|1|0.0|0.0|0.0|nan|nan   
3     [-3.8884213, 19.716284]              3   3|0|2|0.0|nan|nan|nan|nan   
4      [4.6038485, 3.3076212]              7   7|1|0|0.0|0.0|nan|nan|nan   
...  

## Feed parameters into analysis package

In [3]:
onsets = note_df['note_strt']
syntactic_units = note_df['lasso_labels']
expected_interval_range = [0, 1]
dataset_description = 'Songbird: Pied Butcherbirds'

## Find Consistent Transitions

In [4]:
from butcherbird import sequential

In [5]:
import numpy as np

In [6]:
trans_mat = sequential.construct_seq_matrix(note_df, label = 'lasso_labels', sort = False)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [7]:
## bootstrap null distributions with 100 samples under 0-order syntax assumption

In [8]:
p_container = []

## sample 100 times
for i in np.arange(0, 100):
    
    ## bootstrap one zero-order sequence
    bootstrapped_df = note_df.sample(n = len(note_df), replace = True).reset_index()
    
    ## find the transition matrix of the sequence
    bootstrapped_mat = sequential.construct_seq_matrix(bootstrapped_df, label = 'lasso_labels', sort = False)
    
    ## turn the matrix into long form
    bootstrapped_long = sequential.long_cvtr(bootstrapped_mat, songType = 'Bootstrapped')
    
    ## return bootstrapped distribution of all transition probabilities
    p_container.append(bootstrapped_long.p.values)
    
p_container

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 37 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 39 40]
[ 0  1  2 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 32 33 34 35 36 37 38 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 32 33 34 35 36 37 38 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 0 

[array([0.03418803, 0.01709402, 0.03418803, ..., 0.        , 0.03375527,
        0.08860759]),
 array([0.04347826, 0.00869565, 0.00869565, ..., 0.        , 0.02857143,
        0.06122449]),
 array([0.01111111, 0.01111111, 0.03333333, ..., 0.        , 0.02459016,
        0.04508197]),
 array([0.05084746, 0.00847458, 0.02542373, ..., 0.        , 0.02661597,
        0.06463878]),
 array([0.        , 0.        , 0.04854369, ..., 0.        , 0.02469136,
        0.05761317]),
 array([0.05217391, 0.0173913 , 0.02608696, ..., 0.        , 0.02834008,
        0.06477733]),
 array([0.02941176, 0.00980392, 0.04901961, ..., 0.        , 0.05381166,
        0.0896861 ]),
 array([0.04958678, 0.        , 0.02479339, ..., 0.        , 0.01239669,
        0.07024793]),
 array([0.        , 0.00892857, 0.03571429, ..., 0.        , 0.0376569 ,
        0.10041841]),
 array([0.01785714, 0.        , 0.03571429, ..., 0.        , 0.0412844 ,
        0.03211009]),
 array([0.04761905, 0.01904762, 0.00952381, ..., 0

In [9]:
## swap axes so that each element in p_container is a null sampling distribution of 
## find how likely that specific transition happpens with just 0 order syntax

In [10]:
p = np.swapaxes(p_container, 0, 1)

In [11]:
p

array([[0.03418803, 0.04347826, 0.01111111, ..., 0.03092784, 0.01438849,
        0.02678571],
       [0.01709402, 0.00869565, 0.01111111, ..., 0.01030928, 0.        ,
        0.        ],
       [0.03418803, 0.00869565, 0.03333333, ..., 0.04123711, 0.03597122,
        0.03571429],
       ...,
       [0.        , 0.        , 0.        , ..., 0.00429185, 0.        ,
        0.        ],
       [0.03375527, 0.02857143, 0.02459016, ..., 0.0472103 , 0.02380952,
        0.02      ],
       [0.08860759, 0.06122449, 0.04508197, ..., 0.07725322, 0.07539683,
        0.072     ]])

In [12]:
import numpy as np
import scipy.stats

## a standard calculation for confidence interval
def mean_confidence_interval(data, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1 + confidence) / 2., n-1)
    return m, m-h, m+h

In [13]:
higherconfints = []

for null_transitions in p:
    higherconfints.append(mean_confidence_interval(null_transitions, confidence = 0.95)[2])
    
higherconfints

[0.030597915136109648,
 0.013328929395761755,
 0.030959461297615964,
 0.025874962311297312,
 0.006394901274257253,
 0.01940723382876536,
 0.056296711004796614,
 0.026819925097370006,
 0.012465871717377796,
 0.020630097533560165,
 0.030503133947985334,
 0.022357805357452736,
 0.009254820113329423,
 0.01685744013802468,
 0.02944765379575497,
 0.029382719081772434,
 0.02668692536205243,
 0.038594909134407225,
 0.027304291287425703,
 0.030206007551528195,
 0.033518640034435075,
 0.08107977465500357,
 0.0017772754246714539,
 0.09552057124666204,
 0.08391386059836427,
 0.01644444836697328,
 0.021961560996250348,
 0.011055946824427648,
 0.04568928821144479,
 0.08402342632642654,
 0.0020926671664333865,
 0.0012362727616614386,
 0.0007851087722033934,
 0.0013913630345870223,
 0.006165789427788774,
 0.0015122413448087663,
 0.000615718194854881,
 0.012927590237784701,
 0.0,
 0.02696701564853796,
 0.07397359521405411,
 0.036547014682677265,
 0.011877065452047916,
 0.027695188585474616,
 0.03282921

In [14]:
trans_long = sequential.long_cvtr(trans_mat, songType = 'True')

In [15]:
trans_long

songType  noteType  markov         p
0        True         0       0  0.000000
1        True         0       1  0.000000
2        True         0       2  0.000000
3        True         0       3  0.876190
4        True         0       4  0.000000
...       ...       ...     ...       ...
1676     True        40      36  0.000000
1677     True        40      37  0.000000
1678     True        40      38  0.000000
1679     True        40      39  0.044534
1680     True        40      40  0.230769

[1681 rows x 4 columns]

In [16]:
trans_long['higherconfint'] = higherconfints

In [17]:
trans_long

songType  noteType  markov         p  higherconfint
0        True         0       0  0.000000       0.030598
1        True         0       1  0.000000       0.013329
2        True         0       2  0.000000       0.030959
3        True         0       3  0.876190       0.025875
4        True         0       4  0.000000       0.006395
...       ...       ...     ...       ...            ...
1676     True        40      36  0.000000       0.001125
1677     True        40      37  0.000000       0.012030
1678     True        40      38  0.000000       0.000538
1679     True        40      39  0.044534       0.027232
1680     True        40      40  0.230769       0.073215

[1681 rows x 5 columns]

In [18]:
filtered_trans_long = trans_long[trans_long.p > trans_long.higherconfint]

In [19]:
filtered_trans_long

songType  noteType  markov         p  higherconfint
3        True         0       3  0.876190       0.025875
50       True         1       9  0.029412       0.021430
51       True         1      10  0.294118       0.031952
61       True         1      20  0.088235       0.032684
64       True         1      23  0.205882       0.093424
...       ...       ...     ...       ...            ...
1651     True        40      11  0.170040       0.020945
1654     True        40      14  0.251012       0.027869
1656     True        40      16  0.157895       0.027791
1679     True        40      39  0.044534       0.027232
1680     True        40      40  0.230769       0.073215

[164 rows x 5 columns]

In [20]:
ftl = filtered_trans_long

## Rhythm Dyadic Analysis

In [21]:
## load rhythm analyzer
import butcherbird.rhythm as rhythm

/home/AD/j8xing/syntax_rhythm_pbb/butcherbird/rhythm.py:151: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


In [22]:
dyadic = rhythm.construct_rhythm_df(
    onsets = onsets, 
    syntactic_units = syntactic_units, 
    expected_interval_range = expected_interval_range)

In [23]:
dyadic

intervals1  intervals2  label1  label2  label3  s_interval  l_interval  \
746     0.018920    0.015573      26      26       5    0.015573    0.018920   
1275    0.049143    0.007020      39      26      39    0.007020    0.049143   
2146    0.054145    0.019306      39      26       6    0.019306    0.054145   
12      0.042565    0.048240      27      28       8    0.042565    0.048240   
2634    0.055795    0.056753      25      40      14    0.055795    0.056753   
...          ...         ...     ...     ...     ...         ...         ...   
509     0.555021    0.895000      20      18       6    0.555021    0.895000   
1609    0.707663    0.752358      20      18       0    0.707663    0.752358   
427     0.670000    0.830021      20      16       0    0.670000    0.830021   
3343    0.555399    0.965593      19       1      23    0.555399    0.965593   
1143    0.792418    0.737603      20      18       0    0.737603    0.792418   

      cycle_dur  ratio_roeske  ratio_custom  cycle_rank  
746    0.034493      0.548518      0.823094           1  
1275   0.056163      0.875000      0.142857           2  
2146   0.073452      0.737159      0.356560           3  
12     0.090806      0.468750      0.882353           4  
2634   0.112549      0.495744      0.983118           5  
...         ...           ...           ...         ...  
509    1.450021      0.382767      0.620135        2295  
1609   1.460021      0.484694      0.940593        2296  
427    1.500021      0.446660      0.807209        2297  
3343   1.520993      0.365156      0.575190        2298  
1143   1.530021      0.517913      0.930825        2299  

[2299 rows x 11 columns]

In [24]:
ftl

songType  noteType  markov         p  higherconfint
3        True         0       3  0.876190       0.025875
50       True         1       9  0.029412       0.021430
51       True         1      10  0.294118       0.031952
61       True         1      20  0.088235       0.032684
64       True         1      23  0.205882       0.093424
...       ...       ...     ...       ...            ...
1651     True        40      11  0.170040       0.020945
1654     True        40      14  0.251012       0.027869
1656     True        40      16  0.157895       0.027791
1679     True        40      39  0.044534       0.027232
1680     True        40      40  0.230769       0.073215

[164 rows x 5 columns]

In [25]:
## verify rhythm counts above 0.01 of total rhythm count (8013 * 0.01)

In [26]:
verified = []

for index, transition in ftl.iterrows():
    note = transition.noteType
    dest = transition.markov
    
    ## find if dyadic contains enough entries for this particular combination
    first_filter = dyadic[dyadic.label1 == note]
    second_filter = first_filter[first_filter.label2 == dest]
    
    if len(second_filter) > 0.01*len(dyadic):
        verified.append(index)

In [27]:
vr = ftl.filter(items = verified, axis = 0)

In [28]:
unique, counts = np.unique(vr.noteType, return_counts = True)

In [29]:
eligible_notes = []
for noteType, count in zip(unique, counts):
    if count > 1:
        eligible_notes.append(noteType)

In [30]:
eligible_transitions = []

for n in eligible_notes:
    eligible_transitions.append(vr[vr.noteType == n])
    
eligible_transitions = pd.concat(eligible_transitions)

In [31]:
eligible_transitions

songType  noteType  markov         p  higherconfint
261      True         6      15  0.317204       0.026356
286      True         6      40  0.381720       0.075723
326      True         7      39  0.510638       0.028399
327      True         7      40  0.414894       0.067657
669      True        16      13  0.438202       0.015700
681      True        16      25  0.528090       0.015047
723      True        17      26  0.271318       0.021516
725      True        17      28  0.581395       0.047985
884      True        21      23  0.369963       0.094085
890      True        21      29  0.241758       0.076967
945      True        23       2  0.289389       0.026367
960      True        23      17  0.382637       0.039877
970      True        23      27  0.083601       0.011969
980      True        23      37  0.102894       0.012362
1003     True        24      19  0.274436       0.030198
1008     True        24      24  0.406015       0.076246
1154     True        28       6  0.465409       0.055713
1171     True        28      23  0.515723       0.091752
1656     True        40      16  0.157895       0.027791
1680     True        40      40  0.230769       0.073215

In [32]:
import scipy.stats

def bif_rhythm_ks(vd_bif, dyadic, mode = 'ratio_roeske'):
    '''
    Calculate KS test for each bifurcation point
    '''
    
    output = []
    
    # 1. Extract Bifurcation Info from vd_bif
    ### a. Find all pre-bifurcation notes
    pre_bif = np.unique(vd_bif['noteType'])
    
    # 2. For each bifurcation, conduct a Kolmogorov-Smirnov test
    ### a. for each bifurcation
    for note in pre_bif:
        ### a. Query its exact slice
        bif_df = vd_bif[vd_bif['noteType'] == note]
        ### b. Query its bifurcation destinations (assumes only 2)
        t1 = bif_df['markov'].values[0]
        t2 = bif_df['markov'].values[1]
        ### c. Filter dyadic by pre_bif
        note_df = dyadic[dyadic['label1'] == note]
        ### d. Filter note_df by bif destinations
        t1_df = note_df[note_df['label2'] == t1]
        t2_df = note_df[note_df['label2'] == t2]
        ### e. compute ks
        try:
            ks = scipy.stats.ks_2samp(t1_df[mode], t2_df[mode])
        except:
            ks = [None, None]
            print('ks not computed')
        ### e. feeds out pandas
        output.append(
            pd.DataFrame(
                {
                    'pre_bif': [note],
                    'bif_des': [(t1, t2)],
                    'bif_prof': [
                        (
                            bif_df['p'].values[0],
                            bif_df['p'].values[1]
                        )
                    ],
                    'rhy_cnts': [
                        (
                            len(t1_df),
                            len(t2_df)
                        )
                    ],
                    'ks_statistic': [ks[0]],
                    'ks_p': [ks[1]]
                }
            )
        )
        
        print('Finished querying bifurcation with pre_bif ', note)
    return pd.concat(output)

In [33]:
entangle = bif_rhythm_ks(eligible_transitions, dyadic)

Finished querying bifurcation with pre_bif  6
Finished querying bifurcation with pre_bif  7
Finished querying bifurcation with pre_bif  16
Finished querying bifurcation with pre_bif  17
Finished querying bifurcation with pre_bif  21
Finished querying bifurcation with pre_bif  23
Finished querying bifurcation with pre_bif  24
Finished querying bifurcation with pre_bif  28
Finished querying bifurcation with pre_bif  40


In [34]:
entangle

pre_bif   bif_des                                    bif_prof   rhy_cnts  \
0        6  (15, 40)    (0.3172043010752688, 0.3817204301075269)   (59, 70)   
0        7  (39, 40)    (0.5106382978723404, 0.4148936170212766)   (48, 39)   
0       16  (13, 25)   (0.43820224719101125, 0.5280898876404494)   (39, 47)   
0       17  (26, 28)    (0.2713178294573643, 0.5813953488372093)   (34, 75)   
0       21  (23, 29)     (0.36996336996337, 0.24175824175824176)  (100, 66)   
0       23   (2, 17)  (0.28938906752411575, 0.38263665594855306)  (90, 117)   
0       24  (19, 24)   (0.2744360902255639, 0.40601503759398494)   (26, 70)   
0       28   (6, 23)   (0.46540880503144655, 0.5157232704402516)   (69, 82)   
0       40  (16, 40)  (0.15789473684210525, 0.23076923076923078)   (39, 39)   

   ks_statistic          ks_p  
0      0.985714  4.007376e-36  
0      0.485577  3.730388e-05  
0      0.748500  3.465592e-12  
0      0.134118  7.335003e-01  
0      0.974848  9.869535e-44  
0      0.264957  1.217930e-03  
0      0.586813  1.209256e-06  
0      0.131495  4.833624e-01  
0      1.000000  7.348344e-23

In [35]:
entangle['ks_p'] < 0.001

0     True
0     True
0     True
0    False
0     True
0    False
0     True
0    False
0     True
Name: ks_p, dtype: bool

In [36]:
## bonferroni correct

In [37]:
import statsmodels.stats.multitest

In [38]:
entangle['bonferroni_p'] = statsmodels.stats.multitest.multipletests(entangle['ks_p'].values, alpha = 0.05, method = 'bonferroni')[1]

In [39]:
entangle

pre_bif   bif_des                                    bif_prof   rhy_cnts  \
0        6  (15, 40)    (0.3172043010752688, 0.3817204301075269)   (59, 70)   
0        7  (39, 40)    (0.5106382978723404, 0.4148936170212766)   (48, 39)   
0       16  (13, 25)   (0.43820224719101125, 0.5280898876404494)   (39, 47)   
0       17  (26, 28)    (0.2713178294573643, 0.5813953488372093)   (34, 75)   
0       21  (23, 29)     (0.36996336996337, 0.24175824175824176)  (100, 66)   
0       23   (2, 17)  (0.28938906752411575, 0.38263665594855306)  (90, 117)   
0       24  (19, 24)   (0.2744360902255639, 0.40601503759398494)   (26, 70)   
0       28   (6, 23)   (0.46540880503144655, 0.5157232704402516)   (69, 82)   
0       40  (16, 40)  (0.15789473684210525, 0.23076923076923078)   (39, 39)   

   ks_statistic          ks_p  bonferroni_p  
0      0.985714  4.007376e-36  3.606638e-35  
0      0.485577  3.730388e-05  3.357349e-04  
0      0.748500  3.465592e-12  3.119033e-11  
0      0.134118  7.335003e-01  1.000000e+00  
0      0.974848  9.869535e-44  8.882582e-43  
0      0.264957  1.217930e-03  1.096137e-02  
0      0.586813  1.209256e-06  1.088331e-05  
0      0.131495  4.833624e-01  1.000000e+00  
0      1.000000  7.348344e-23  6.613510e-22

In [56]:
entangle['bonferroni_p'] < 0.05

0     True
0     True
0     True
0    False
0     True
0     True
0     True
0    False
0     True
Name: bonferroni_p, dtype: bool

In [41]:
## do a shuffle
dyadic_shuffle = dyadic.copy(deep = True)
np.random.shuffle(dyadic_shuffle['ratio_roeske'].values)
entangle_shuffled = bif_rhythm_ks(eligible_transitions, dyadic_shuffle)

Finished querying bifurcation with pre_bif  6
Finished querying bifurcation with pre_bif  7
Finished querying bifurcation with pre_bif  16
Finished querying bifurcation with pre_bif  17
Finished querying bifurcation with pre_bif  21
Finished querying bifurcation with pre_bif  23
Finished querying bifurcation with pre_bif  24
Finished querying bifurcation with pre_bif  28
Finished querying bifurcation with pre_bif  40


In [42]:
entangle_shuffled

pre_bif   bif_des                                    bif_prof   rhy_cnts  \
0        6  (15, 40)    (0.3172043010752688, 0.3817204301075269)   (59, 70)   
0        7  (39, 40)    (0.5106382978723404, 0.4148936170212766)   (48, 39)   
0       16  (13, 25)   (0.43820224719101125, 0.5280898876404494)   (39, 47)   
0       17  (26, 28)    (0.2713178294573643, 0.5813953488372093)   (34, 75)   
0       21  (23, 29)     (0.36996336996337, 0.24175824175824176)  (100, 66)   
0       23   (2, 17)  (0.28938906752411575, 0.38263665594855306)  (90, 117)   
0       24  (19, 24)   (0.2744360902255639, 0.40601503759398494)   (26, 70)   
0       28   (6, 23)   (0.46540880503144655, 0.5157232704402516)   (69, 82)   
0       40  (16, 40)  (0.15789473684210525, 0.23076923076923078)   (39, 39)   

   ks_statistic      ks_p  
0      0.198789  0.133766  
0      0.150641  0.646067  
0      0.189853  0.366082  
0      0.263137  0.062756  
0      0.156061  0.253172  
0      0.079487  0.874130  
0      0.153846  0.694640  
0      0.087487  0.903091  
0      0.230769  0.252313

# Compute Global Statistic

The concept of the global statistic here is to compare the rhythm ratios for each first-order syntax and to compare between-group variation / within-group variation. 

1. Find each first-order transition -> z-score -> compile all first-order transition -> MSE
2. Compare with zero-order transition -> z-score -> compile all first-order transition -> MSE
3. Is first-order transition variance is lower than zero-order transition variance?

## Let's find all the first-order transitions first

In [43]:
import scipy.stats as stats

In [44]:
def syntactic_rhythmic_modulation_metric (dyadic):
    
    ## compute global metric
    
    first_order_rhythms_centered = []
    first_order_group_n = 0

    ## for every possible label
    for label in np.unique(dyadic['label1']):

        ## find a sub dataframe containing only designated zero-order label
        zero_order = dyadic[dyadic['label1'] == label]

        ## for every possible transition of that label
        for transition in np.unique(zero_order['label2']):

            ## find its rhythms
            first_order = zero_order[zero_order['label2'] == transition]
            first_order_rhythms = first_order['ratio_roeske'].values
            first_order_rhythms_centered.extend(first_order_rhythms - np.mean(first_order_rhythms))

            ## add 1 to group_n
            first_order_group_n+=1
    
    # find MSE
    MSE_first = sum(np.square(first_order_rhythms_centered)) / len(dyadic)
    MSE_baseline = sum(np.square(dyadic['ratio_roeske'].values - np.mean(dyadic['ratio_roeske']))) / len(dyadic)
    
    return 1 - MSE_first / MSE_baseline

## empirical 

In [45]:
syntactic_rhythmic_modulation_metric(dyadic)

0.9505825335678296

## Find Baseline using bootstrap

In [46]:
from tqdm.autonotebook import tqdm

In [47]:
dyadic_shuffle = dyadic.copy(deep = True)

SDoMSE = []

for sample in tqdm(np.arange(0, 100)):
    
    ## shuffle dyadic
    np.random.shuffle(dyadic_shuffle['ratio_roeske'].values)
    
    SDoMSE.append(syntactic_rhythmic_modulation_metric(dyadic_shuffle))

  0%|          | 0/100 [00:00<?, ?it/s]

In [48]:
mean_confidence_interval(SDoMSE, confidence=0.95)

(0.07128759793849357, 0.07019558765382064, 0.0723796082231665)

In [49]:
syntactic_rhythmic_modulation_metric(dyadic)

0.9505825335678296

## try using anova

In [50]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [51]:
dyadic = dyadic.astype({'label1': str, 'label2': str})

In [52]:
model = ols('ratio_roeske ~ label1', data = dyadic).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
anova_table

sum_sq      df           F  PR(>F)
label1    66.859079    38.0  144.412532     0.0
Residual  27.534700  2260.0         NaN     NaN

In [53]:
dyadic['transition'] = dyadic['label1'] + '+' + dyadic['label2']

In [54]:
dyadic

intervals1  intervals2 label1 label2  label3  s_interval  l_interval  \
746     0.018920    0.015573     26     26       5    0.015573    0.018920   
1275    0.049143    0.007020     39     26      39    0.007020    0.049143   
2146    0.054145    0.019306     39     26       6    0.019306    0.054145   
12      0.042565    0.048240     27     28       8    0.042565    0.048240   
2634    0.055795    0.056753     25     40      14    0.055795    0.056753   
...          ...         ...    ...    ...     ...         ...         ...   
509     0.555021    0.895000     20     18       6    0.555021    0.895000   
1609    0.707663    0.752358     20     18       0    0.707663    0.752358   
427     0.670000    0.830021     20     16       0    0.670000    0.830021   
3343    0.555399    0.965593     19      1      23    0.555399    0.965593   
1143    0.792418    0.737603     20     18       0    0.737603    0.792418   

      cycle_dur  ratio_roeske  ratio_custom  cycle_rank transition  
746    0.034493      0.548518      0.823094           1      26+26  
1275   0.056163      0.875000      0.142857           2      39+26  
2146   0.073452      0.737159      0.356560           3      39+26  
12     0.090806      0.468750      0.882353           4      27+28  
2634   0.112549      0.495744      0.983118           5      25+40  
...         ...           ...           ...         ...        ...  
509    1.450021      0.382767      0.620135        2295      20+18  
1609   1.460021      0.484694      0.940593        2296      20+18  
427    1.500021      0.446660      0.807209        2297      20+16  
3343   1.520993      0.365156      0.575190        2298       19+1  
1143   1.530021      0.517913      0.930825        2299      20+18  

[2299 rows x 12 columns]

In [55]:
model = ols('ratio_roeske ~ transition', data = dyadic).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
anova_table

sum_sq      df           F  PR(>F)
transition  89.729077   165.0  248.665918     0.0
Residual     4.664701  2133.0         NaN     NaN