***
# 3.1 First Order Syntax for Bird 26
### JX, 03/15/2022
***
    Bird26:
    LS110395.9.28.2017PalmRagonesi.WAV
    
***

In [1]:
indv = 'Bird26'

In [2]:
## Load up Note Dataframe

import pandas as pd
from pathlib2 import Path

from butcherbird.utils.paths import DATA_DIR

SAVE_LOC = 'interim/fine_labels/butcherbird_note_df_'+indv+'_fine.pickle'
SAVE_LOC = DATA_DIR / SAVE_LOC

note_df = pd.read_pickle(SAVE_LOC)

## Make a copy of recursively generated labels
#note_df['lasso_labels'] = note_df['recur_labels_id']

note_df

phrase_nb  phrase_strt   phrase_end  phrase_len  note_cnt  note_nb  \
0              0     2.530000     3.108940    0.578940         4        0   
1              0     2.530000     3.108940    0.578940         4        1   
2              0     2.530000     3.108940    0.578940         4        2   
3              0     2.530000     3.108940    0.578940         4        3   
4              1     7.660000     9.269842    1.609842         6        0   
...          ...          ...          ...         ...       ...      ...   
10861       1426  7451.938961  7454.270021    2.331060        11        6   
10862       1426  7451.938961  7454.270021    2.331060        11        7   
10863       1426  7451.938961  7454.270021    2.331060        11        8   
10864       1426  7451.938961  7454.270021    2.331060        11        9   
10865       1426  7451.938961  7454.270021    2.331060        11       10   

         note_strt     note_end  note_len    indv  indvi  \
0         2.530000     2.565308  0.035308  Bird26      0   
1         2.582859     2.646042  0.063184  Bird26      0   
2         2.754858     2.877196  0.122338  Bird26      0   
3         2.942109     3.108940  0.166831  Bird26      0   
4         7.660000     7.802573  0.142573  Bird26      0   
...            ...          ...       ...     ...    ...   
10861  7453.230000  7453.347846  0.117846  Bird26      0   
10862  7453.430000  7453.582862  0.152862  Bird26      0   
10863  7453.582862  7453.644792  0.061930  Bird26      0   
10864  7453.786119  7453.917918  0.131800  Bird26      0   
10865  7454.046542  7454.270021  0.223479  Bird26      0   

                                     key  \
0      LS110395.9.28.2017PalmRagonesi_dn   
1      LS110395.9.28.2017PalmRagonesi_dn   
2      LS110395.9.28.2017PalmRagonesi_dn   
3      LS110395.9.28.2017PalmRagonesi_dn   
4      LS110395.9.28.2017PalmRagonesi_dn   
...                                  ...   
10861  LS110395.9.28.2017PalmRagonesi_dn   
10862  LS110395.9.28.2017PalmRagonesi_dn   
10863  LS110395.9.28.2017PalmRagonesi_dn   
10864  LS110395.9.28.2017PalmRagonesi_dn   
10865  LS110395.9.28.2017PalmRagonesi_dn   

                                                   audio   rate  \
0      [0.0, 1.046653124410034e-05, 2.781446748131873...  48000   
1      [-0.0, -5.34641467372343e-06, -1.1688967129128...  48000   
2      [0.0, 2.4410663172602654e-05, 5.92200898084064...  48000   
3      [-0.0, -0.00015404379157812003, -0.00030952889...  48000   
4      [0.0, 5.444124866051962e-05, 0.000182190384940...  48000   
...                                                  ...    ...   
10861  [0.0, 0.00020218813079315542, 0.00039304040322...  48000   
10862  [-0.0, -6.027892231941223e-05, -0.000147847971...  48000   
10863  [-0.0, -0.0007704722401279731, -0.002082758701...  48000   
10864  [-0.0, -2.3817842366836413e-06, -8.17539332897...  48000   
10865  [0.0, 0.0008279382682486668, 0.001595642342663...  48000   

                                             spectrogram  \
0      [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
1      [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
2      [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
3      [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
4      [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
...                                                  ...   
10861  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
10862  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
10863  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
10864  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
10865  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   

                           umap  hdbscan_labels  \
0        [-7.5537066, 8.209083]              21   
1        [-0.6834063, 9.239816]              11   
2       [-1.5902307, -12.39612]               0   
3        [7.0395265, 3.0541244]              26   
4       [5.1442027, -3.2366111]              12   


## Feed parameters into analysis package

In [3]:
onsets = note_df['note_strt']
syntactic_units = note_df['lasso_labels']
expected_interval_range = [0, 1]
dataset_description = 'Songbird: Pied Butcherbirds'

## Find Consistent Transitions

In [4]:
from butcherbird import sequential

In [5]:
import numpy as np

In [6]:
trans_mat = sequential.construct_seq_matrix(note_df, label = 'lasso_labels', sort = False)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]


In [7]:
## bootstrap null distributions with 100 samples under 0-order syntax assumption

In [8]:
p_container = []

## sample 100 times
for i in np.arange(0, 100):
    
    ## bootstrap one zero-order sequence
    bootstrapped_df = note_df.sample(n = len(note_df), replace = True).reset_index()
    
    ## find the transition matrix of the sequence
    bootstrapped_mat = sequential.construct_seq_matrix(bootstrapped_df, label = 'lasso_labels', sort = False)
    
    ## turn the matrix into long form
    bootstrapped_long = sequential.long_cvtr(bootstrapped_mat, songType = 'Bootstrapped')
    
    ## return bootstrapped distribution of all transition probabilities
    p_container.append(bootstrapped_long.p.values)
    
p_container

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28

[array([0.03217822, 0.01237624, 0.05445545, ..., 0.02272727, 0.02272727,
        0.02272727]),
 array([0.03430079, 0.00527704, 0.06068602, ..., 0.01851852, 0.01851852,
        0.        ]),
 array([0.03252033, 0.01626016, 0.05149051, ..., 0.11111111, 0.        ,
        0.        ]),
 array([0.03504043, 0.00269542, 0.08625337, ..., 0.06818182, 0.        ,
        0.        ]),
 array([0.04092072, 0.01278772, 0.06905371, ..., 0.04      , 0.        ,
        0.        ]),
 array([0.04197531, 0.01481481, 0.09135802, ..., 0.03703704, 0.        ,
        0.        ]),
 array([0.02393617, 0.0106383 , 0.08244681, ..., 0.10416667, 0.        ,
        0.02083333]),
 array([0.03350515, 0.00257732, 0.07216495, ..., 0.15217391, 0.        ,
        0.        ]),
 array([0.02832861, 0.01983003, 0.07365439, ..., 0.        , 0.        ,
        0.01923077]),
 array([0.0252809 , 0.01685393, 0.06179775, ..., 0.03448276, 0.        ,
        0.01724138]),
 array([0.04807692, 0.01442308, 0.08173077, ..., 0

In [9]:
## swap axes so that each element in p_container is a null sampling distribution of 
## find how likely that specific transition happpens with just 0 order syntax

In [10]:
p = np.swapaxes(p_container, 0, 1)

In [11]:
p

array([[0.03217822, 0.03430079, 0.03252033, ..., 0.01554404, 0.04761905,
        0.03743316],
       [0.01237624, 0.00527704, 0.01626016, ..., 0.01295337, 0.00529101,
        0.00802139],
       [0.05445545, 0.06068602, 0.05149051, ..., 0.09067358, 0.06878307,
        0.0802139 ],
       ...,
       [0.02272727, 0.01851852, 0.11111111, ..., 0.        , 0.04444444,
        0.        ],
       [0.02272727, 0.01851852, 0.        , ..., 0.05405405, 0.        ,
        0.        ],
       [0.02272727, 0.        , 0.        , ..., 0.        , 0.        ,
        0.02857143]])

In [12]:
import numpy as np
import scipy.stats

## a standard calculation for confidence interval
def mean_confidence_interval(data, confidence=0.95):
    a = 1.0 * np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1 + confidence) / 2., n-1)
    return m, m-h, m+h

In [13]:
higherconfints = []

for null_transitions in p:
    higherconfints.append(mean_confidence_interval(null_transitions, confidence = 0.95)[2])
    
higherconfints

[0.03815043894705507,
 0.01081796960222381,
 0.07660609756565108,
 0.002466940850620683,
 0.07024622871285777,
 0.017112340345713253,
 0.038925229815522884,
 0.017399684091651012,
 0.0520245439675401,
 0.043024904909905244,
 0.03528262356415739,
 0.011518838721715195,
 0.009878895286257593,
 0.026755967541041255,
 0.035304732956710924,
 0.0445893035489365,
 0.029609302475114674,
 0.019827950345492316,
 0.020474567295265284,
 0.03917252030959216,
 0.037347870861621064,
 0.039271146920641244,
 0.021201144688231942,
 0.022873847835008475,
 0.047017116294809494,
 0.007700775747999783,
 0.024811550005639782,
 0.03374478932198413,
 0.03976496717353013,
 0.004117252541539443,
 0.003812025145763371,
 0.004800551148787715,
 0.03760296094529712,
 0.033484172720008205,
 0.044600155727100035,
 0.010054597287632278,
 0.00474446661667306,
 0.039250226065398436,
 0.012279996209713928,
 0.07705295506522544,
 0.004428675940665764,
 0.07107006362102548,
 0.01834247094158087,
 0.041318261095723625,
 0.01

In [14]:
trans_long = sequential.long_cvtr(trans_mat, songType = 'True')

In [15]:
trans_long

songType  noteType  markov         p
0        True         0       0  0.000000
1        True         0       1  0.000000
2        True         0       2  0.000000
3        True         0       3  0.000000
4        True         0       4  0.005155
...       ...       ...     ...       ...
1364     True        36      32  0.085106
1365     True        36      33  0.000000
1366     True        36      34  0.000000
1367     True        36      35  0.000000
1368     True        36      36  0.000000

[1369 rows x 4 columns]

In [16]:
trans_long['higherconfint'] = higherconfints

In [17]:
trans_long

songType  noteType  markov         p  higherconfint
0        True         0       0  0.000000       0.038150
1        True         0       1  0.000000       0.010818
2        True         0       2  0.000000       0.076606
3        True         0       3  0.000000       0.002467
4        True         0       4  0.005155       0.070246
...       ...       ...     ...       ...            ...
1364     True        36      32  0.085106       0.037928
1365     True        36      33  0.000000       0.035469
1366     True        36      34  0.000000       0.044823
1367     True        36      35  0.000000       0.008764
1368     True        36      36  0.000000       0.007584

[1369 rows x 5 columns]

In [18]:
filtered_trans_long = trans_long[trans_long.p > trans_long.higherconfint]

In [19]:
filtered_trans_long

songType  noteType  markov         p  higherconfint
5        True         0       5  0.018041       0.017112
19       True         0      19  0.953608       0.039173
52       True         1      15  0.819820       0.043332
68       True         1      31  0.045045       0.004781
69       True         1      32  0.063063       0.038152
...       ...       ...     ...       ...            ...
1261     True        34       3  0.028825       0.003073
1264     True        34       6  0.889135       0.041869
1329     True        35      34  0.968085       0.048949
1347     True        36      15  0.893617       0.051895
1364     True        36      32  0.085106       0.037928

[164 rows x 5 columns]

In [20]:
ftl = filtered_trans_long

## Rhythm Dyadic Analysis

In [21]:
## load rhythm analyzer
import butcherbird.rhythm as rhythm

/home/AD/j8xing/syntax_rhythm_pbb/butcherbird/rhythm.py:151: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


In [22]:
dyadic = rhythm.construct_rhythm_df(
    onsets = onsets, 
    syntactic_units = syntactic_units, 
    expected_interval_range = expected_interval_range)

In [23]:
dyadic

intervals1  intervals2  label1  label2  label3  s_interval  l_interval  \
1897    0.036661    0.018330       4       4       2    0.018330    0.036661   
4525    0.045403    0.011351       4      30       2    0.011351    0.045403   
246     0.036661    0.020622       4       4       2    0.020622    0.036661   
4125    0.039727    0.024593       4       4       2    0.024593    0.039727   
3490    0.049186    0.018837       8       4      24    0.018837    0.049186   
...          ...         ...     ...     ...     ...         ...         ...   
6068    0.424074    0.665907       9      33      22    0.424074    0.665907   
8981    0.849679    0.266775       2      33      34    0.266775    0.849679   
6945    0.600683    0.540571       9      31      17    0.540571    0.600683   
1127    0.710000    0.437014      20      34      34    0.437014    0.710000   
5144    0.903264    0.290000      12      33      34    0.290000    0.903264   

      cycle_dur  ratio_roeske  ratio_custom  cycle_rank  
1897   0.054991      0.666667      0.500000           1  
4525   0.056753      0.800000      0.250000           2  
246    0.057282      0.640000      0.562500           3  
4125   0.064321      0.617647      0.619048           4  
3490   0.068024      0.723078      0.382977           5  
...         ...           ...           ...         ...  
6068   1.089982      0.389066      0.636837        8009  
8981   1.116454      0.761051      0.313972        8010  
6945   1.141254      0.526336      0.899927        8011  
1127   1.147014      0.618999      0.615512        8012  
5144   1.193264      0.756969      0.321058        8013  

[8013 rows x 11 columns]

In [24]:
ftl

songType  noteType  markov         p  higherconfint
5        True         0       5  0.018041       0.017112
19       True         0      19  0.953608       0.039173
52       True         1      15  0.819820       0.043332
68       True         1      31  0.045045       0.004781
69       True         1      32  0.063063       0.038152
...       ...       ...     ...       ...            ...
1261     True        34       3  0.028825       0.003073
1264     True        34       6  0.889135       0.041869
1329     True        35      34  0.968085       0.048949
1347     True        36      15  0.893617       0.051895
1364     True        36      32  0.085106       0.037928

[164 rows x 5 columns]

In [25]:
## verify rhythm counts above 0.01 of total rhythm count (8013 * 0.01)

In [26]:
verified = []

for index, transition in ftl.iterrows():
    note = transition.noteType
    dest = transition.markov
    
    ## find if dyadic contains enough entries for this particular combination
    first_filter = dyadic[dyadic.label1 == note]
    second_filter = first_filter[first_filter.label2 == dest]
    
    if len(second_filter) > 0.01*len(dyadic):
        verified.append(index)

In [27]:
vr = ftl.filter(items = verified, axis = 0)

In [28]:
unique, counts = np.unique(vr.noteType, return_counts = True)

In [29]:
eligible_notes = []
for noteType, count in zip(unique, counts):
    if count > 1:
        eligible_notes.append(noteType)

In [30]:
eligible_transitions = []

for n in eligible_notes:
    eligible_transitions.append(vr[vr.noteType == n])
    
eligible_transitions = pd.concat(eligible_transitions)

In [31]:
eligible_transitions

songType  noteType  markov         p  higherconfint
74       True         2       0  0.345432       0.036130
95       True         2      21  0.513141       0.039852
356      True         9      23  0.442661       0.022997
366      True         9      33  0.373853       0.035937
564      True        15       9  0.615741       0.040958
588      True        15      33  0.275463       0.034500
792      True        21      15  0.287411       0.040271
803      True        21      26  0.605701       0.024762
916      True        24      28  0.296000       0.040687
920      True        24      32  0.640000       0.037522
1192     True        32       8  0.597911       0.055110
1194     True        32      10  0.334204       0.031765

In [32]:
import scipy.stats

def bif_rhythm_ks(vd_bif, dyadic, mode = 'ratio_roeske'):
    '''
    Calculate KS test for each bifurcation point
    '''
    
    output = []
    
    # 1. Extract Bifurcation Info from vd_bif
    ### a. Find all pre-bifurcation notes
    pre_bif = np.unique(vd_bif['noteType'])
    
    # 2. For each bifurcation, conduct a Kolmogorov-Smirnov test
    ### a. for each bifurcation
    for note in pre_bif:
        ### a. Query its exact slice
        bif_df = vd_bif[vd_bif['noteType'] == note]
        ### b. Query its bifurcation destinations (assumes only 2)
        t1 = bif_df['markov'].values[0]
        t2 = bif_df['markov'].values[1]
        ### c. Filter dyadic by pre_bif
        note_df = dyadic[dyadic['label1'] == note]
        ### d. Filter note_df by bif destinations
        t1_df = note_df[note_df['label2'] == t1]
        t2_df = note_df[note_df['label2'] == t2]
        ### e. compute ks
        try:
            ks = scipy.stats.ks_2samp(t1_df[mode], t2_df[mode])
        except:
            ks = [None, None]
            print('ks not computed')
        ### e. feeds out pandas
        output.append(
            pd.DataFrame(
                {
                    'pre_bif': [note],
                    'bif_des': [(t1, t2)],
                    'bif_prof': [
                        (
                            bif_df['p'].values[0],
                            bif_df['p'].values[1]
                        )
                    ],
                    'rhy_cnts': [
                        (
                            len(t1_df),
                            len(t2_df)
                        )
                    ],
                    'ks_statistic': [ks[0]],
                    'ks_p': [ks[1]]
                }
            )
        )
        
        print('Finished querying bifurcation with pre_bif ', note)
    return pd.concat(output)

In [33]:
entangle = bif_rhythm_ks(eligible_transitions, dyadic)

Finished querying bifurcation with pre_bif  2
Finished querying bifurcation with pre_bif  9
Finished querying bifurcation with pre_bif  15
Finished querying bifurcation with pre_bif  21
Finished querying bifurcation with pre_bif  24
Finished querying bifurcation with pre_bif  32


In [34]:
entangle

pre_bif   bif_des                                   bif_prof    rhy_cnts  \
0        2   (0, 21)   (0.3454317897371715, 0.5131414267834794)  (276, 410)   
0        9  (23, 33)   (0.4426605504587156, 0.3738532110091743)  (178, 160)   
0       15   (9, 33)  (0.6157407407407407, 0.27546296296296297)  (246, 116)   
0       21  (15, 26)  (0.28741092636579574, 0.6057007125890737)  (121, 255)   
0       24  (28, 32)                              (0.296, 0.64)  (148, 320)   
0       32   (8, 10)    (0.597911227154047, 0.3342036553524804)  (229, 128)   

   ks_statistic           ks_p  
0      0.883634  3.160450e-136  
0      0.254635   2.631016e-05  
0      0.991379   7.899610e-94  
0      1.000000  1.179450e-101  
0      0.590878   1.884640e-33  
0      0.356100   8.782928e-10

In [35]:
entangle['ks_p'] < 0.001

0    True
0    True
0    True
0    True
0    True
0    True
Name: ks_p, dtype: bool

In [36]:
## bonferroni correct

In [37]:
import statsmodels.stats.multitest

In [65]:
entangle['bonferroni_p'] = statsmodels.stats.multitest.multipletests(entangle['ks_p'].values, alpha = 0.05, method = 'bonferroni')[1]

In [66]:
entangle

pre_bif   bif_des                                   bif_prof    rhy_cnts  \
0        2   (0, 21)   (0.3454317897371715, 0.5131414267834794)  (276, 410)   
0        9  (23, 33)   (0.4426605504587156, 0.3738532110091743)  (178, 160)   
0       15   (9, 33)  (0.6157407407407407, 0.27546296296296297)  (246, 116)   
0       21  (15, 26)  (0.28741092636579574, 0.6057007125890737)  (121, 255)   
0       24  (28, 32)                              (0.296, 0.64)  (148, 320)   
0       32   (8, 10)    (0.597911227154047, 0.3342036553524804)  (229, 128)   

   ks_statistic           ks_p   bonferroni_p  
0      0.883634  3.160450e-136  1.896270e-135  
0      0.254635   2.631016e-05   1.578609e-04  
0      0.991379   7.899610e-94   4.739766e-93  
0      1.000000  1.179450e-101  7.076702e-101  
0      0.590878   1.884640e-33   1.130784e-32  
0      0.356100   8.782928e-10   5.269757e-09

In [67]:
entangle['bonferroni_p'] < 0.001

0    True
0    True
0    True
0    True
0    True
0    True
Name: bonferroni_p, dtype: bool

In [39]:
## do a shuffle
dyadic_shuffle = dyadic.copy(deep = True)
np.random.shuffle(dyadic_shuffle['ratio_roeske'].values)
entangle_shuffled = bif_rhythm_ks(eligible_transitions, dyadic_shuffle)

Finished querying bifurcation with pre_bif  2
Finished querying bifurcation with pre_bif  9
Finished querying bifurcation with pre_bif  15
Finished querying bifurcation with pre_bif  21
Finished querying bifurcation with pre_bif  24
Finished querying bifurcation with pre_bif  32


In [40]:
entangle_shuffled

pre_bif   bif_des                                   bif_prof    rhy_cnts  \
0        2   (0, 21)   (0.3454317897371715, 0.5131414267834794)  (276, 410)   
0        9  (23, 33)   (0.4426605504587156, 0.3738532110091743)  (178, 160)   
0       15   (9, 33)  (0.6157407407407407, 0.27546296296296297)  (246, 116)   
0       21  (15, 26)  (0.28741092636579574, 0.6057007125890737)  (121, 255)   
0       24  (28, 32)                              (0.296, 0.64)  (148, 320)   
0       32   (8, 10)    (0.597911227154047, 0.3342036553524804)  (229, 128)   

   ks_statistic      ks_p  
0      0.069176  0.386148  
0      0.088132  0.492767  
0      0.076465  0.708918  
0      0.157479  0.029760  
0      0.105321  0.194156  
0      0.105111  0.297916

# Compute Global Statistic

The concept of the global statistic here is to compare the rhythm ratios for each first-order syntax and to compare between-group variation / within-group variation. 

1. Find each first-order transition -> z-score -> compile all first-order transition -> MSE
2. Compare with zero-order transition -> z-score -> compile all first-order transition -> MSE
3. Is first-order transition variance is lower than zero-order transition variance?

## Let's find all the first-order transitions first

In [41]:
import scipy.stats as stats

In [42]:
def syntactic_rhythmic_modulation_metric (dyadic):
    
    ## compute global metric
    
    first_order_rhythms_centered = []
    first_order_group_n = 0

    ## for every possible label
    for label in np.unique(dyadic['label1']):

        ## find a sub dataframe containing only designated zero-order label
        zero_order = dyadic[dyadic['label1'] == label]

        ## for every possible transition of that label
        for transition in np.unique(zero_order['label2']):

            ## find its rhythms
            first_order = zero_order[zero_order['label2'] == transition]
            first_order_rhythms = first_order['ratio_roeske'].values
            first_order_rhythms_centered.extend(first_order_rhythms - np.mean(first_order_rhythms))

            ## add 1 to group_n
            first_order_group_n+=1
    
    # find MSE
    MSE_first = sum(np.square(first_order_rhythms_centered)) / len(dyadic)
    MSE_baseline = sum(np.square(dyadic['ratio_roeske'].values - np.mean(dyadic['ratio_roeske']))) / len(dyadic)
    
    return 1 - MSE_first / MSE_baseline

## empirical 

In [43]:
syntactic_rhythmic_modulation_metric(dyadic)

0.9544513632274816

## Find Baseline using bootstrap

In [44]:
from tqdm.autonotebook import tqdm

In [45]:
dyadic_shuffle = dyadic.copy(deep = True)

SDoMSE = []

for sample in tqdm(np.arange(0, 100)):
    
    ## shuffle dyadic
    np.random.shuffle(dyadic_shuffle['ratio_roeske'].values)
    
    SDoMSE.append(syntactic_rhythmic_modulation_metric(dyadic_shuffle))

  0%|          | 0/100 [00:00<?, ?it/s]

In [46]:
mean_confidence_interval(SDoMSE, confidence=0.95)

(0.03114152589081614, 0.03060868051567416, 0.03167437126595812)

In [47]:
syntactic_rhythmic_modulation_metric(dyadic)

0.9544513632274816

## try using anova

In [48]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [49]:
dyadic = dyadic.astype({'label1': str, 'label2': str})

In [50]:
model = ols('ratio_roeske ~ label1', data = dyadic).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
anova_table

sum_sq      df           F  PR(>F)
label1    258.014632    36.0  760.350559     0.0
Residual   75.181868  7976.0         NaN     NaN

In [51]:
dyadic['transition'] = dyadic['label1'] + '+' + dyadic['label2']

In [52]:
dyadic

intervals1  intervals2 label1 label2  label3  s_interval  l_interval  \
1897    0.036661    0.018330      4      4       2    0.018330    0.036661   
4525    0.045403    0.011351      4     30       2    0.011351    0.045403   
246     0.036661    0.020622      4      4       2    0.020622    0.036661   
4125    0.039727    0.024593      4      4       2    0.024593    0.039727   
3490    0.049186    0.018837      8      4      24    0.018837    0.049186   
...          ...         ...    ...    ...     ...         ...         ...   
6068    0.424074    0.665907      9     33      22    0.424074    0.665907   
8981    0.849679    0.266775      2     33      34    0.266775    0.849679   
6945    0.600683    0.540571      9     31      17    0.540571    0.600683   
1127    0.710000    0.437014     20     34      34    0.437014    0.710000   
5144    0.903264    0.290000     12     33      34    0.290000    0.903264   

      cycle_dur  ratio_roeske  ratio_custom  cycle_rank transition  
1897   0.054991      0.666667      0.500000           1        4+4  
4525   0.056753      0.800000      0.250000           2       4+30  
246    0.057282      0.640000      0.562500           3        4+4  
4125   0.064321      0.617647      0.619048           4        4+4  
3490   0.068024      0.723078      0.382977           5        8+4  
...         ...           ...           ...         ...        ...  
6068   1.089982      0.389066      0.636837        8009       9+33  
8981   1.116454      0.761051      0.313972        8010       2+33  
6945   1.141254      0.526336      0.899927        8011       9+31  
1127   1.147014      0.618999      0.615512        8012      20+34  
5144   1.193264      0.756969      0.321058        8013      12+33  

[8013 rows x 12 columns]

In [53]:
model = ols('ratio_roeske ~ transition', data = dyadic).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
anova_table

sum_sq      df           F  PR(>F)
transition  318.019854   246.0  661.516526     0.0
Residual     15.176646  7766.0         NaN     NaN